# This is a basic workflow that is manually triggered

name: XMAS Dev Manual Youtube Videos

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Output filename prefix'
        # Default value if no value is explicitly provided
        default: 'xmasdev'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  makevideo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: workflow
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      #with:
      #  path: main
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - name: Setup yt-dlp
      uses: AnimMouse/setup-yt-dlp@v1
      with:
        with-ffmpeg: true
# Runs a single command using the runners shell
      #echo "Hello ${{ github.event.inputs.name }}"
    - name: create video files
      #shell: bash
      run: |
        cd XMASDEV/2022/banners/Source
        bash createyoutubevideos.sh createyoutubevideos.json

    - name: commit new files
      #shell: bash
      run: |
        git config user.email ${{ secrets.GIT_USERNAME }}
        git config user.name ${{ secrets.GIT_NAME }}
        git add .
        git commit -m 'created video file'
        git push -f origin master 
